# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fc8ca2f62ee66356d425baf7f8bce6796b032a66f8d076c22fe996b9b7693b5f45aeac6246e4ade3a0ead0f9b7ed7b197c10de2df99c783cdf6ebaf2c24c614

test:
  secret_key_base: 95ef6772223be6ea41ee92ba00f4300b54702f6d66c300711b2378a86a8a9d60c44789051162b805dc0c31a0ac8c1801460d0e85ecb0c07d7248374476f8ee3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
